rule all:
    input:
        "final_data.h5ad"

rule preprocess_data:
    output:
        "preprocessed_data.h5ad"
    script:
        "preprocess_data.py"

rule qc:
    input:
        "preprocessed_data.h5ad"
    output:
        "qc_data.h5ad"
    script:
        "qc.py"

rule normalize_data:
    input:
        "qc_data.h5ad"
    output:
        "normalized_data.h5ad"
    script:
        "normalize_data.py"

rule pca_analysis:
    input:
        "normalized_data.h5ad"
    output:
        "pca_data.h5ad"
    script:
        "pca_analysis.py"

rule umap_clustering:
    input:
        "pca_data.h5ad"
    output:
        "umap_data.h5ad"
    script:
        "umap_clustering.py"

rule differential_expression:
    input:
        "umap_data.h5ad"
    output:
        "final_data.h5ad"
    script:
        "differential_expression.py"